version: '3.9'

services:
  db:
    env_file:
      - .env
    image: postgres
    restart: always
    shm_size: 512mb
    ports:
      - '5431:5431'
    command: -p 5431
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
